name: CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install code checking tools
        run: |
          python -m pip install --upgrade pip setuptools
          pip install black flake8
      - name: Check codestyle
        run: black --check flask_storm/ tests/ setup.py
      - name: Run linting
        run: flake8 flask_storm/ tests/ setup.py

  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]
        storm-package:
          - storm
          - storm-legacy
    name: Py ${{ matrix.python-version }} with ${{ matrix.storm-package }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -e .[dev,fancy]
      - name: Install ${{ matrix.storm-package }}
        run: pip install ${{ matrix.storm-package }}
      - name: Run test suite
        run: pytest
